""" from Junior_2025_Main import *


checkBluetoothButton()
checkLeftButton()

print(kirby.hub.battery.voltage(), "mv") #bateria de kirby en miliVolts
wait(10)

timer = StopWatch()
kirby.driveDegrees(-600,MID_SPEED)
kirby.turnInPlace(NORTH)
kirby.driveTime(2000,-MID_SPEED)
kirby.driveDegrees(50,MID_SPEED)
kirby.turnInPlace(WEST)
kirby.driveDegrees(800,MIN_SPEED)
kirby.turnInPlace(NORTH)
kirby.driveDegrees(300,MID_SPEED)
kirby.driveDegrees(200,MIN_SPEED)
kirby.turnInPlace(EAST)
kirby.driveDegrees(-200,MID_SPEED)
kirby.turnInPlace(NORTH)
kirby.driveDegrees(320,MID_SPEED)
kirby.turnInPlace(EAST)
kirby.driveDegrees(100,MID_SPEED)
kirby.moveBackMotorDegrees(-120,700)
kirby.driveDegrees(-200,MID_SPEED)
kirby.moveBackMotorDegrees(0,700)
kirby.driveDegrees(225,MID_SPEED)
kirby.moveFrontMotorDegrees(-100,300)
kirby.moveFrontMotorDegrees(0,300)
kirby.driveDegrees(-125,MID_SPEED)
kirby.turnInPlace(NORTH)
kirby.driveDegrees(-600,MID_SPEED)
kirby.driveTime(2000,-MID_SPEED)
kirby.driveDegrees(50,MID_SPEED)
kirby.turnInPlace(EAST)
kirby.driveDegrees(775,MID_SPEED)
kirby.turnInPlace(SOUTH)
kirby.driveDegrees(-700,MID_SPEED)
kirby.driveTime(2000,-MID_SPEED)
kirby.driveDegrees(50,MID_SPEED)
kirby.turnInPlace(EAST)
kirby.driveDegrees(-170,MID_SPEED)
kirby.turnInPlace(SOUTH)

kirby.driveDegrees(250,MID_SPEED)
kirby.moveFrontMotorDegrees(-100,700)
kirby.turnInPlace(EAST)
kirby.driveDegrees(400,MID_SPEED)
kirby.turnInPlace(SOUTH)
kirby.driveDegrees(400,MID_SPEED)
kirby.moveFrontMotorDegrees(0,700)
kirby.driveDegrees(-450,MID_SPEED)
kirby.turnInPlace(EAST)
kirby.driveDegrees(-450,MID_SPEED)
kirby.turnInPlace(SOUTH)

kirby.driveDegrees(270,MID_SPEED)
kirby.moveFrontMotorDegrees(-100,700)
kirby.turnInPlace(WEST)
kirby.driveDegrees(500,MAX_SPEED)
kirby.turnInPlace(SOUTH)
kirby.driveDegrees(330,MAX_SPEED)
kirby.turnInPlace(WEST)
kirby.driveDegrees(240,MID_SPEED)


print("time:", timer.time() / 1000, "s")
 """